import Link from "next/link";
import { MetricCard } from "@/components/cards/metric-card";
import {
    DonutBreakdownChart,
    GrowthLineChart,
    HorizontalBarChart,
} from "@/components/donor/transparency-charts";
import { PageContainer } from "@/components/layout/page-container";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { ArrowRight, Banknote, BarChart3, Briefcase, GraduationCap, Target, Users } from "lucide-react";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { getDonorDashboardData } from "@/lib/supabase/actions";
import { redirect } from "next/navigation";
import { programGrowth, sectorPlacementBreakdown } from "@/mock-data/donor";

const dashboardIcons = [
    Users,
    Banknote,
    Banknote,
    Target,
    GraduationCap,
    Briefcase,
];

export default async function DonorDashboardPage() {
    const supabase = await createSupabaseServerClient();
    const { data: { user } } = await supabase.auth.getUser();

    if (!user) {
        redirect("/login");
    }

    const {
        profile,
        impactMetrics,
        fundingRecords,
        sponsoredScholars
    } = await getDonorDashboardData(user.id);

    const averageProgress = sponsoredScholars.length > 0
        ? Math.round(sponsoredScholars.reduce((sum: number, scholar: any) => sum + (scholar.progress_score || 0), 0) / sponsoredScholars.length)
        : 0;

    const totalFunding = fundingRecords.reduce((acc: number, curr: any) => acc + Number(curr.amount), 0);
    const formattedTotalFunding = new Intl.NumberFormat("en-NG", { style: "currency", currency: "NGN", maximumFractionDigits: 0 }).format(totalFunding);

    const totalImpact = impactMetrics.reduce((acc: number, curr: any) => acc + (isNaN(Number(curr.value)) ? 0 : Number(curr.value)), 0);
    const formattedImpact = totalImpact >= 1000 ? `${(totalImpact / 1000).toFixed(1)}k` : totalImpact.toString();

    const donorDashboardMetrics = [
        { title: "Sponsored Scholars", value: sponsoredScholars.length.toString(), description: "Active beneficiaries" },
        { title: "Total Deployed", value: formattedTotalFunding, description: "Funding transparently tracked" },
        { title: "Direct Impact", value: formattedImpact, description: "Community reach through scholars" },
        { title: "Placement Rate", value: "88%", description: "Industry deployment success" },
        { title: "Graduation Rate", value: "96%", description: "Completion on-track" },
        { title: "Active Programs", value: "4", description: "Strategic focus areas" },
    ];

    const fundDistribution = fundingRecords.map((f: any) => ({
        label: f.category,
        value: Number(f.amount),
        color: `hsl(var(--primary) / ${0.4 + Math.random() * 0.6})`
    }));

    const scholarOutcomeBreakdown = [
        { label: "High Performance", value: sponsoredScholars.filter((s: any) => (s.progress_score || 0) >= 80).length, color: "var(--primary)" },
        { label: "On Track", value: sponsoredScholars.filter((s: any) => (s.progress_score || 0) >= 60 && (s.progress_score || 0) < 80).length, color: "#f59e0b" },
        { label: "Support Needed", value: sponsoredScholars.filter((s: any) => (s.progress_score || 0) < 60).length, color: "#ef4444" },
    ].map(item => ({
        ...item,
        value: sponsoredScholars.length > 0 ? Math.round((item.value / sponsoredScholars.length) * 100) : 0
    }));

    return (
        <PageContainer
            title="Donor Dashboard"
            description="Track funding transparency, sponsored scholar development, and the impact generated by your support."
            action={
                <Button asChild>
                    <Link href="/donor/funding-allocation">
                        Open Funding Allocation <ArrowRight className="ml-1" />
                    </Link>
                </Button>
            }
        >
            <div className="space-y-6">
                <Card className="border-border/60 bg-[linear-gradient(135deg,rgba(34,197,94,0.10),rgba(255,255,255,0.98)_52%,rgba(237,248,243,0.92))]">
                    <CardContent className="p-6 md:p-8">
                        <div className="grid gap-6 xl:grid-cols-[1.15fr_0.85fr]">
                            <div className="space-y-5">
                                <div>
                                    <div className="flex flex-wrap items-center gap-2">
                                        <h2 className="text-2xl font-semibold tracking-tight">{profile?.organization || "Donor Organization"}</h2>
                                        <Badge variant="secondary">Active Donor</Badge>
                                        <Badge variant="outline">{profile?.donor_id || "DNR-Pending"}</Badge>
                                    </div>
                                    <p className="mt-3 max-w-3xl text-sm leading-6 text-muted-foreground">
                                        {profile?.bio || "No description provided."}
                                    </p>
                                </div>

                                <div className="grid gap-3 sm:grid-cols-2">
                                    <div className="rounded-xl border bg-background/85 p-4">
                                        <p className="text-xs uppercase tracking-[0.22em] text-muted-foreground">Commitment Window</p>
                                        <p className="mt-2 font-semibold">2024 - 2028</p>
                                        <p className="mt-1 text-sm text-muted-foreground">Relationship manager: Support Team</p>
                                    </div>
                                    <div className="rounded-xl border bg-background/85 p-4">
                                        <p className="text-xs uppercase tracking-[0.22em] text-muted-foreground">Total Commitment</p>
                                        <p className="mt-2 text-3xl font-bold tracking-tight">{formattedTotalFunding}</p>
                                        <p className="mt-1 text-sm text-muted-foreground">Transparent across scholar funding and development support.</p>
                                    </div>
                                </div>
                            </div>

                            <div className="rounded-2xl border bg-background/85 p-5 shadow-sm">
                                <p className="text-xs uppercase tracking-[0.22em] text-muted-foreground">Transparency Snapshot</p>
                                <div className="mt-4 space-y-4">
                                    {[
                                        { label: "Funding visibility", value: 100, detail: "Every allocation line is trackable by category and scholar." },
                                        { label: "Scholar development coverage", value: averageProgress, detail: "Sponsored scholars remain on-track across academic and career milestones." },
                                        { label: "Outcome reporting cadence", value: 93, detail: "Quarterly impact packets and annual reports are current." },
                                    ].map((item) => (
                                        <div key={item.label} className="space-y-2">
                                            <div className="flex items-center justify-between gap-4">
                                                <div>
                                                    <p className="font-medium">{item.label}</p>
                                                    <p className="text-xs text-muted-foreground">{item.detail}</p>
                                                </div>
                                                <span className="text-sm font-semibold">{item.value}%</span>
                                            </div>
                                            <Progress value={item.value} className="h-2" />
                                        </div>
                                    ))}
                                </div>
                                <div className="mt-5 rounded-xl border border-primary/20 bg-primary/5 p-4">
                                    <p className="font-medium">Average sponsored scholar progress</p>
                                    <p className="mt-1 text-3xl font-bold tracking-tight">{averageProgress}%</p>
                                    <p className="mt-1 text-xs text-muted-foreground">A composite of academic performance, milestones, and placement readiness.</p>
                                </div>
                            </div>
                        </div>
                    </CardContent>
                </Card>

                <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-6">
                    {donorDashboardMetrics.map((metric, index) => (
                        <MetricCard
                            key={metric.title}
                            title={metric.title}
                            value={metric.value}
                            description={metric.description}
                            icon={dashboardIcons[index]}
                            className="border-border/60"
                        />
                    ))}
                </div>

                <div className="grid gap-6 xl:grid-cols-2">
                    <Card className="border-border/60">
                        <CardHeader>
                            <CardTitle>Fund Distribution</CardTitle>
                            <CardDescription>How donor funding is currently distributed across scholar development.</CardDescription>
                        </CardHeader>
                        <CardContent>
                            <DonutBreakdownChart
                                items={fundDistribution.length > 0 ? fundDistribution : [{ label: "No funding yet", value: 0, color: "var(--muted)" }]}
                                totalLabel="Deployed"
                                totalValue={formattedTotalFunding}
                            />
                        </CardContent>
                    </Card>

                    <Card className="border-border/60">
                        <CardHeader>
                            <CardTitle>Scholar Outcomes</CardTitle>
                            <CardDescription>Outcome segments showing how supported scholars are progressing.</CardDescription>
                        </CardHeader>
                        <CardContent>
                            <HorizontalBarChart items={scholarOutcomeBreakdown} valueSuffix="%" />
                        </CardContent>
                    </Card>

                    <Card className="border-border/60">
                        <CardHeader>
                            <CardTitle>Education Sectors</CardTitle>
                            <CardDescription>Placement and engagement outcomes across priority sectors.</CardDescription>
                        </CardHeader>
                        <CardContent>
                            <HorizontalBarChart items={sectorPlacementBreakdown} valueSuffix="%" />
                        </CardContent>
                    </Card>

                    <Card className="border-border/60">
                        <CardHeader>
                            <CardTitle className="flex items-center gap-2">
                                <BarChart3 className="h-4 w-4 text-primary" />
                                Program Growth
                            </CardTitle>
                            <CardDescription>Growth in donor-backed scholar coverage across recent cycles.</CardDescription>
                        </CardHeader>
                        <CardContent>
                            <GrowthLineChart
                                data={programGrowth}
                                valueLabel="Supported scholars per year across the donor-backed portfolio."
                            />
                        </CardContent>
                    </Card>
                </div>

                <Card className="border-border/60">
                    <CardHeader className="flex flex-row items-start justify-between gap-4">
                        <div>
                            <CardTitle>Scholar Performance Snapshot</CardTitle>
                            <CardDescription>How funding is translating into scholar development outcomes.</CardDescription>
                        </div>
                        <Button asChild variant="outline" size="sm">
                            <Link href="/donor/sponsored-scholars">View Sponsored Scholars</Link>
                        </Button>
                    </CardHeader>
                    <CardContent className="grid gap-4 lg:grid-cols-2">
                        {sponsoredScholars.map((scholar: any) => (
                            <div key={scholar.id} className="rounded-xl border bg-background p-4">
                                <div className="flex items-start gap-3">
                                    <Avatar size="lg" className="h-12 w-12">
                                        <AvatarFallback className="bg-primary/12 font-semibold text-primary">
                                            {scholar.first_name[0]}{scholar.last_name[0]}
                                        </AvatarFallback>
                                    </Avatar>
                                    <div className="flex-1">
                                        <div className="flex flex-wrap items-center gap-2">
                                            <p className="font-semibold">{scholar.first_name} {scholar.last_name}</p>
                                            <Badge variant="outline">Cohort {scholar.cohort}</Badge>
                                        </div>
                                        <p className="text-sm text-muted-foreground">{scholar.program} · {scholar.institution}</p>
                                    </div>
                                    <Badge className="bg-emerald-100 text-emerald-800 hover:bg-emerald-100">
                                        {scholar.progress_score >= 80 ? "Excellent" : scholar.progress_score >= 60 ? "On Track" : "Needs Review"}
                                    </Badge>
                                </div>

                                <div className="mt-4 space-y-2">
                                    <div className="flex items-center justify-between text-sm">
                                        <span className="text-muted-foreground">Development score</span>
                                        <span className="font-semibold">{scholar.progress_score || 0}%</span>
                                    </div>
                                    <Progress value={scholar.progress_score || 0} className="h-2" />
                                </div>

                                <p className="mt-4 text-sm text-muted-foreground">{scholar.bio?.slice(0, 100)}...</p>
                            </div>
                        ))}
                        {sponsoredScholars.length === 0 && (
                            <p className="text-sm text-muted-foreground">No sponsored scholars yet.</p>
                        )}
                    </CardContent>
                </Card>
            </div>
        </PageContainer>
    );
}
