import Link from "next/link";
import { MetricCard } from "@/components/cards/metric-card";
import {
    DonutBreakdownChart,
    GrowthLineChart,
    HorizontalBarChart,
} from "@/components/donor/transparency-charts";
import { PageContainer } from "@/components/layout/page-container";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { ArrowRight, Banknote, BarChart3, Briefcase, GraduationCap, Target, Users } from "lucide-react";
import {
    donorDashboardMetrics,
    donorProfile,
    fundDistribution,
    programGrowth,
    scholarOutcomeBreakdown,
    sectorPlacementBreakdown,
    sponsoredScholars,
} from "@/mock-data/donor";

const dashboardIcons = [
  Users,
  Banknote,
  Banknote,
  Target,
  GraduationCap,
  Briefcase,
];

export default function DonorDashboardPage() {
    const averageProgress = Math.round(
        sponsoredScholars.reduce((sum, scholar) => sum + scholar.progressScore, 0) / Math.max(sponsoredScholars.length, 1)
    );

    return (
        <PageContainer
            title="Donor Dashboard"
            description="Track funding transparency, sponsored scholar development, and the impact generated by your support."
            action={
                <Button asChild>
                    <Link href="/donor/funding-allocation">
                        Open Funding Allocation <ArrowRight className="ml-1" />
                    </Link>
                </Button>
            }
        >
            <div className="space-y-6">
                <Card className="border-border/60 bg-[linear-gradient(135deg,rgba(34,197,94,0.10),rgba(255,255,255,0.98)_52%,rgba(237,248,243,0.92))]">
                    <CardContent className="p-6 md:p-8">
                        <div className="grid gap-6 xl:grid-cols-[1.15fr_0.85fr]">
                            <div className="space-y-5">
                                <div>
                                    <div className="flex flex-wrap items-center gap-2">
                                        <h2 className="text-2xl font-semibold tracking-tight">{donorProfile.organization}</h2>
                                        <Badge variant="secondary">Active Donor</Badge>
                                        <Badge variant="outline">{donorProfile.donorId}</Badge>
                                    </div>
                                    <p className="mt-3 max-w-3xl text-sm leading-6 text-muted-foreground">
                                        {donorProfile.focus}
                                    </p>
                                </div>

                                <div className="grid gap-3 sm:grid-cols-2">
                                    <div className="rounded-xl border bg-background/85 p-4">
                                        <p className="text-xs uppercase tracking-[0.22em] text-muted-foreground">Commitment Window</p>
                                        <p className="mt-2 font-semibold">{donorProfile.pledgeWindow}</p>
                                        <p className="mt-1 text-sm text-muted-foreground">Relationship manager: {donorProfile.relationshipManager}</p>
                                    </div>
                                    <div className="rounded-xl border bg-background/85 p-4">
                                        <p className="text-xs uppercase tracking-[0.22em] text-muted-foreground">Total Commitment</p>
                                        <p className="mt-2 text-3xl font-bold tracking-tight">{donorProfile.totalCommitment}</p>
                                        <p className="mt-1 text-sm text-muted-foreground">Transparent across scholar funding and development support.</p>
                                    </div>
                                </div>
                            </div>

                            <div className="rounded-2xl border bg-background/85 p-5 shadow-sm">
                                <p className="text-xs uppercase tracking-[0.22em] text-muted-foreground">Transparency Snapshot</p>
                                <div className="mt-4 space-y-4">
                                    {[
                                        { label: "Funding visibility", value: 100, detail: "Every allocation line is trackable by category and scholar." },
                                        { label: "Scholar development coverage", value: 88, detail: "Sponsored scholars remain on-track across academic and career milestones." },
                                        { label: "Outcome reporting cadence", value: 93, detail: "Quarterly impact packets and annual reports are current." },
                                    ].map((item) => (
                                        <div key={item.label} className="space-y-2">
                                            <div className="flex items-center justify-between gap-4">
                                                <div>
                                                    <p className="font-medium">{item.label}</p>
                                                    <p className="text-xs text-muted-foreground">{item.detail}</p>
                                                </div>
                                                <span className="text-sm font-semibold">{item.value}%</span>
                                            </div>
                                            <Progress value={item.value} className="h-2" />
                                        </div>
                                    ))}
                                </div>
                                <div className="mt-5 rounded-xl border border-primary/20 bg-primary/5 p-4">
                                    <p className="font-medium">Average sponsored scholar progress</p>
                                    <p className="mt-1 text-3xl font-bold tracking-tight">{averageProgress}%</p>
                                    <p className="mt-1 text-xs text-muted-foreground">A composite of academic performance, milestones, and placement readiness.</p>
                                </div>
                            </div>
                        </div>
                    </CardContent>
                </Card>

                <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-6">
                    {donorDashboardMetrics.map((metric, index) => (
                        <MetricCard
                            key={metric.title}
                            title={metric.title}
                            value={metric.value}
                            description={metric.description}
                            icon={dashboardIcons[index]}
                            className="border-border/60"
                        />
                    ))}
                </div>

                <div className="grid gap-6 xl:grid-cols-2">
                    <Card className="border-border/60">
                        <CardHeader>
                            <CardTitle>Fund Distribution</CardTitle>
                            <CardDescription>How donor funding is currently distributed across scholar development.</CardDescription>
                        </CardHeader>
                        <CardContent>
                            <DonutBreakdownChart
                                items={fundDistribution}
                                totalLabel="Deployed"
                                totalValue="₦14.2M"
                            />
                        </CardContent>
                    </Card>

                    <Card className="border-border/60">
                        <CardHeader>
                            <CardTitle>Scholar Outcomes</CardTitle>
                            <CardDescription>Outcome segments showing how supported scholars are progressing.</CardDescription>
                        </CardHeader>
                        <CardContent>
                            <HorizontalBarChart items={scholarOutcomeBreakdown} valueSuffix="%" />
                        </CardContent>
                    </Card>

                    <Card className="border-border/60">
                        <CardHeader>
                            <CardTitle>Education Sectors</CardTitle>
                            <CardDescription>Placement and engagement outcomes across priority sectors.</CardDescription>
                        </CardHeader>
                        <CardContent>
                            <HorizontalBarChart items={sectorPlacementBreakdown} valueSuffix="%" />
                        </CardContent>
                    </Card>

                    <Card className="border-border/60">
                        <CardHeader>
                            <CardTitle className="flex items-center gap-2">
                                <BarChart3 className="h-4 w-4 text-primary" />
                                Program Growth
                            </CardTitle>
                            <CardDescription>Growth in donor-backed scholar coverage across recent cycles.</CardDescription>
                        </CardHeader>
                        <CardContent>
                            <GrowthLineChart
                                data={programGrowth}
                                valueLabel="Supported scholars per year across the donor-backed portfolio."
                            />
                        </CardContent>
                    </Card>
                </div>

                <Card className="border-border/60">
                    <CardHeader className="flex flex-row items-start justify-between gap-4">
                        <div>
                            <CardTitle>Scholar Performance Snapshot</CardTitle>
                            <CardDescription>How funding is translating into scholar development outcomes.</CardDescription>
                        </div>
                        <Button asChild variant="outline" size="sm">
                            <Link href="/donor/sponsored-scholars">View Sponsored Scholars</Link>
                        </Button>
                    </CardHeader>
                    <CardContent className="grid gap-4 lg:grid-cols-2">
                        {sponsoredScholars.map((scholar) => (
                            <div key={scholar.id} className="rounded-xl border bg-background p-4">
                                <div className="flex items-start gap-3">
                                    <Avatar size="lg" className="h-12 w-12">
                                        <AvatarFallback className="bg-primary/12 font-semibold text-primary">
                                            {scholar.initials}
                                        </AvatarFallback>
                                    </Avatar>
                                    <div className="flex-1">
                                        <div className="flex flex-wrap items-center gap-2">
                                            <p className="font-semibold">{scholar.name}</p>
                                            <Badge variant="outline">Cohort {scholar.cohort}</Badge>
                                        </div>
                                        <p className="text-sm text-muted-foreground">{scholar.program} · {scholar.institution}</p>
                                    </div>
                                    <Badge className="bg-emerald-100 text-emerald-800 hover:bg-emerald-100">
                                        {scholar.performance}
                                    </Badge>
                                </div>

                                <div className="mt-4 space-y-2">
                                    <div className="flex items-center justify-between text-sm">
                                        <span className="text-muted-foreground">Development score</span>
                                        <span className="font-semibold">{scholar.progressScore}%</span>
                                    </div>
                                    <Progress value={scholar.progressScore} className="h-2" />
                                </div>

                                <div className="mt-4 grid gap-3 sm:grid-cols-2">
                                    <div className="rounded-lg bg-muted/20 p-3">
                                        <p className="text-xs uppercase tracking-[0.2em] text-muted-foreground">Allocated</p>
                                        <p className="mt-2 font-semibold">{scholar.allocation}</p>
                                    </div>
                                    <div className="rounded-lg bg-muted/20 p-3">
                                        <p className="text-xs uppercase tracking-[0.2em] text-muted-foreground">Used</p>
                                        <p className="mt-2 font-semibold">{scholar.used}</p>
                                    </div>
                                </div>

                                <p className="mt-4 text-sm text-muted-foreground">{scholar.impact}</p>
                            </div>
                        ))}
                    </CardContent>
                </Card>
            </div>
        </PageContainer>
    );
}
