import { Scholar, Milestone, Placement, UploadedDocument } from "@/types";

export const mockCohorts = [
    {
        id: "c-2024",
        year: "2024",
        phase: "Active Placement",
        applicantsCount: 1482,
        activeScholarsCount: 864,
        reviewCompletion: 100,
        fundingReleased: "₦1.8B",
        readiness: "Ready",
    },
    {
        id: "c-2025",
        year: "2025",
        phase: "Selection Stage",
        applicantsCount: 1840,
        activeScholarsCount: 0,
        reviewCompletion: 42,
        fundingReleased: "₦0.0B",
        readiness: "In Progress",
    },
];

export const mockScholars: Scholar[] = [
    {
        id: "sch-1",
        applicantId: "usr-5",
        cohortId: "c-2024",
        programId: "prog-tech",
        name: "Amara Okafor",
        cohort: "2024",
        discipline: "Data Science for Public Systems",
        institution: "University of Lagos",
        state: "Anambra",
        placement: "NITDA Innovation Lab",
        status: "active",
        progressScore: 84,
        mentorId: "usr-2",
        placementId: "pl-1",
        fundingUtilisation: 76,
        level: "Year 3",
    },
    {
        id: "sch-2",
        applicantId: "usr-6",
        cohortId: "c-2024",
        programId: "prog-health",
        name: "Aisha Mohammed",
        cohort: "2024",
        discipline: "Health Informatics",
        institution: "University of Ibadan",
        state: "Kano",
        placement: "National Health Institute",
        status: "graduated",
        progressScore: 96,
        mentorId: "usr-3",
        placementId: "pl-2",
        fundingUtilisation: 91,
        level: "Graduate",
    },
    {
        id: "sch-3",
        applicantId: "usr-7",
        cohortId: "c-2024",
        programId: "prog-energy",
        name: "Zainab Yusuf",
        cohort: "2024",
        discipline: "Renewable Energy Systems",
        institution: "Ahmadu Bello University",
        state: "Kaduna",
        placement: "Green Future Trust",
        status: "active",
        progressScore: 88,
        mentorId: "usr-4",
        placementId: "pl-3",
        fundingUtilisation: 82,
        level: "Year 4",
    },
    {
        id: "sch-4",
        applicantId: "usr-8",
        cohortId: "c-2023",
        programId: "prog-tech",
        name: "Chukwuemeka Okoro",
        cohort: "2023",
        discipline: "Software Engineering",
        institution: "Covenant University",
        state: "Enugu",
        placement: "FinTech Innovation Hub",
        status: "graduated",
        progressScore: 94,
        mentorId: "usr-2",
        placementId: "pl-4",
        fundingUtilisation: 89,
        level: "Graduate",
    },
];

export const mockMilestones: Milestone[] = [
    {
        id: "m-1",
        scholarId: "sch-1",
        title: "Complete advanced analytics core modules",
        category: "course completion",
        status: "completed",
        dueDate: "2026-02-14",
    },
    {
        id: "m-2",
        scholarId: "sch-1",
        title: "Finish NITDA policy analytics internship",
        category: "internships",
        status: "active",
        dueDate: "2026-05-30",
    },
];

export const mockPlacements: Placement[] = [
    {
        id: "pl-1",
        scholarId: "sch-1",
        organizationName: "NITDA Innovation Lab",
        role: "Data Policy Intern",
        status: "active",
        location: "Abuja",
        startDate: "2026-02-01",
    },
    {
        id: "pl-2",
        scholarId: "sch-2",
        organizationName: "National Health Institute",
        role: "Health Data Analyst",
        status: "completed",
        location: "Abuja",
        startDate: "2025-08-01",
        endDate: "2026-02-28",
    },
    {
        id: "pl-3",
        scholarId: "sch-3",
        organizationName: "Green Future Trust",
        role: "Energy Systems Associate",
        status: "active",
        location: "Kaduna",
        startDate: "2026-01-12",
    },
    {
        id: "pl-4",
        scholarId: "sch-4",
        organizationName: "FinTech Innovation Hub",
        role: "Platform Engineer",
        status: "completed",
        location: "Lagos",
        startDate: "2025-05-01",
        endDate: "2026-01-15",
    },
];

export const mockScholarDocuments: UploadedDocument[] = [
    {
        id: "doc-1",
        type: "transcript",
        name: "Semester 5 Transcript.pdf",
        size: 1024 * 1024 * 1.2,
        uploadedAt: "2026-02-15",
        status: "verified",
    },
    {
        id: "doc-2",
        type: "id",
        name: "National ID Card.jpg",
        size: 1024 * 512,
        uploadedAt: "2025-01-10",
        status: "expiring",
    },
];
