import { User } from "@/types";

export const mockUsers: User[] = [
    {
        id: "usr-1",
        name: "Miriam Okoro",
        email: "m.okoro@ntdi.gov.ng",
        role: "admin",
        team: "Programme Office",
        access: "Super Admin",
        status: "Active",
        lastActive: "2 mins ago",
        avatarUrl: "/avatars/admin-1.png",
    },
    {
        id: "usr-2",
        name: "David Uche",
        email: "d.uche@ntdi.gov.ng",
        role: "reviewer",
        team: "Selection Board A",
        access: "Reviewer Plus",
        status: "Active",
        lastActive: "1 hour ago",
    },
    {
        id: "usr-3",
        name: "Halima Bello",
        email: "h.bello@ntdi.gov.ng",
        role: "reviewer",
        team: "Selection Board B",
        access: "Standard Reviewer",
        status: "Active",
        lastActive: "3 hours ago",
    },
    {
        id: "usr-4",
        name: "Crescent Impact Fund",
        email: "partnerships@crescent.org",
        role: "donor",
        team: "External Partners",
        access: "Audit Only",
        status: "Active",
        lastActive: "Yesterday",
    },
    {
        id: "usr-5",
        name: "Amara Okafor",
        email: "amara.okafor@example.org",
        role: "scholar",
        access: "Scholar Portal",
        status: "Active",
        lastActive: "10 mins ago",
        avatarUrl: "/avatar-1.png",
    },
    {
        id: "usr-6",
        name: "Amina Yusuf",
        email: "amina.yusuf@example.org",
        role: "applicant",
        access: "Applicant Portal",
        status: "Active",
        lastActive: "Just now",
    },
];
